name: Deploy .NET App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Publish .NET App
      run: dotnet publish -c Release

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SCP
      run: |
        scp -o StrictHostKeyChecking=no -r ./bin/Release/net8.0/publish/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.APP_DIR }}

    - name: Restart App Service
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          sudo systemctl restart yourapp
        EOF
