name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master  # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Or 7.0.x if using .NET 7

    - name: Publish Blazor Server app
      run: |
        dotnet publish -c Release -o publish

    - name: Upload to Droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "publish/*"
        target: "/var/www/blazorapp"

    - name: Restart Blazor app (optional)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pkill dotnet || true
          nohup dotnet /var/www/blazorapp/ivs-ui.dll &
